spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mombe_db
    username: shelton
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 2021
